## 1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy. Полученные значения должны быть равны. Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков, а затем с использованием функций из библиотек numpy и pandas.

In [21]:
import numpy as np
import math
import pandas as pd

In [22]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

#### Находим ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy. Полученные значения должны быть равны.

In [23]:
cov = np.round(np.mean(zp*ks) - np.mean(zp)*np.mean(ks), 2)
cov

9157.84

In [24]:
np.cov(zp, ks, ddof=0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

#### Находим коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков, а затем с использованием функций из библиотек numpy и pandas

In [25]:
r = np.cov(zp, ks, ddof=0) / (np.std(zp, ddof=0) * np.std(ks, ddof=0))
r

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

In [26]:
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [27]:
df = pd.DataFrame({'zp':zp, 'ks':ks})
df.corr()

zp       ks
zp  1.00000  0.88749
ks  0.88749  1.00000

## 2. Измерены значения IQ выборки студентов, обучающихся в местных технических вузах: 131, 125, 115, 122, 131, 115, 107, 99, 125, 111. Известно, что в генеральной совокупности IQ распределен нормально. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [29]:
iq = [131, 125, 115, 122, 131, 115, 107, 99, 125, 111]

m = np.mean(iq)
s = np.std(iq, ddof=1)
n = len(iq)
df = n - 1

p = 0.05
t = 2.2622

print(f'Доверительный интервал: [{np.round(m - t * s / math.sqrt(n), 4)}, {np.round(m + t * s / math.sqrt(n), 4)}]')

Доверительный интервал: [110.5559, 125.6441]


## 3. Известно, что рост футболистов в сборной распределен нормально с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27, среднее выборочное составляет 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [30]:
m = 174.2
d = 25
s = math.sqrt(d)
n = 27
df = n - 1

p = 0.05
t = 1.96

print(f'Доверительный интервал: [{np.round(m - t * s / math.sqrt(n), 4)}, {np.round(m + t * s / math.sqrt(n), 4)}]')

Доверительный интервал: [172.314, 176.086]
